// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWLqO0xQiIaqQua_e8rLxjrS1ArcSdKsU',
    appId: '1:913311621141:web:04f3e50035c91e1df62e1c',
    messagingSenderId: '913311621141',
    projectId: 'application-7916f',
    authDomain: 'application-7916f.firebaseapp.com',
    databaseURL: 'https://application-7916f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-7916f.appspot.com',
    measurementId: 'G-EFJ7Z4K29L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYnbtFj_VgNmllo7MqAdHxEqvoThEqHU0',
    appId: '1:913311621141:android:759e8198a0535deef62e1c',
    messagingSenderId: '913311621141',
    projectId: 'application-7916f',
    databaseURL: 'https://application-7916f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-7916f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2a8UeTQz8iKpSTDnqIkkLVHgU3OVBsqY',
    appId: '1:913311621141:ios:b1d10e298278ce74f62e1c',
    messagingSenderId: '913311621141',
    projectId: 'application-7916f',
    databaseURL: 'https://application-7916f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-7916f.appspot.com',
    iosClientId: '913311621141-otkj7blgekgvdkojts09ki25ff5oa0ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2a8UeTQz8iKpSTDnqIkkLVHgU3OVBsqY',
    appId: '1:913311621141:ios:b1d10e298278ce74f62e1c',
    messagingSenderId: '913311621141',
    projectId: 'application-7916f',
    databaseURL: 'https://application-7916f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-7916f.appspot.com',
    iosClientId: '913311621141-otkj7blgekgvdkojts09ki25ff5oa0ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
